### ISSUE TITLE
It should apply a limit for its aggregations?

### ISSUE THREAD

**Issue by alexhoma** [puntmig/php-search#6]
When filtering by some value, it returns a set of aggregations without limit number.

https://github.com/puntmig/php-search/blob/3dea1271fd70a03348612e6bf3e883fb2dae8fe2/Query/Query.php#L421

**Comment by dbeecham** [comment]
This is a pretty fuzzy question is seems! I'm not sure I'm the right guy for the job here, but at the very least I can be a talking rubber duck for a second.

What problem are we trying to solve here? Is it a question of whether or not this piece of code will be able to handle very large results? Or is it a question of where to apply limits?

If it's the latter, then, well, it seems to me that the right place to do limiting is afterwards, i.e. something like `Query::createMatchAll()->filterBy(something)->limit(10)`. This code is generalized in such a way that it's hard to get into the code base, so I can't really gather whether or not you use generators - if you do, then it would be natural to create a "limit" generator which stops yielding after a while. If you don't, well, then I guess you can do limiting afterwards anyway, since whatever is feeding `filterBy` data will need to store the entire result set in memory anyway, and you'd have bigger issues to handle.

**Comment by mmoreram** [comment]
Making a filter and an aggregation should be different things, although they can be related somehow.
So, filterBy method, and unless you specify the other way, will create a limitless aggregation.
If you want to create a limitted aggregation, then you specifically should call aggregateBy with the same filterName parameter. Then you'll be able to set the limit :)

**Comment by dbeecham** [comment]
Hmm, wait. Is filterBy an aggregation? Or do you mean aggregations applied after filterBy, e.g. `Query()->filterBy()->sum() `? I'm not sure I follow. 
Also, how do you want to separate aggregations and filters?

**Comment by mmoreram** [comment]
@dbeecham nopes. filterBy is just a filter. You can filter by _X_ without the need of aggregating the data (for example, for a search box), or you can aggregate the data without the need of filtering anything (for example, for creating menus).

Both filter and aggregations are separated by different methods :)

BTW, are you using this library? I mean, do you want a sandbox to use it?
Anything, please, don't hesitate to write me at marc@puntmig.com :)

Thanks for the feedback!

**Comment by dbeecham** [comment]
No, I just wanted to make github a bit more social. It's easier to get involved in ideas when you see others doing the same, so by just jumping in will at the very least make it easier for the next guy to actually help out.  :) I don't have time to work on this myself, sorry. Hopefully I managed to inspire an idea or two.
